# docker/grafana/provisioning/datasources/datasources.yml
# Grafana 데이터소스 자동 프로비저닝

apiVersion: 1

datasources:
  # Prometheus (메트릭)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  # Loki (로그)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false

  # MySQL (직접 쿼리)
  - name: MySQL
    type: mysql
    url: mysql:3306
    database: lms
    user: lms
    secureJsonData:
      password: lms_password
    editable: false
